name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working_directory: ./web

jobs:
  test:
    name: 'Run Unit tests'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        name: 'Checkout respository'
      
      - name: 'Installing dependencies'
        run: npm i
      
      - name: 'Running Tests'
        run: npm run test
